// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MonDbContext))]
    partial class MonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Avis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Notes")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("Avis");
                });

            modelBuilder.Entity("Data.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Data.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomSeo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devenez pro et créer votre site web avec spring boot et angular",
                            Nom = "Créer votre site web avec spring boot et angular",
                            NomSeo = "spring-angular"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Créer votre application mobile avec flutter étape par étape",
                            Nom = "Créer votre application mobile avec flutter",
                            NomSeo = "flutter"
                        },
                        new
                        {
                            Id = 3,
                            Description = "comment faire du code propre",
                            Nom = "Apprendre le clean code",
                            NomSeo = "clean-code"
                        },
                        new
                        {
                            Id = 4,
                            Description = "gérer votre base de donnée",
                            Nom = "Devenez pro gestion de base de donnée",
                            NomSeo = "base-de-donnee"
                        },
                        new
                        {
                            Id = 5,
                            Description = "comment faire du C",
                            Nom = "Apprendre le C",
                            NomSeo = "langage-C"
                        },
                        new
                        {
                            Id = 6,
                            Description = "La conception de l'architecture est une étape cruciale du développement logiciel",
                            Nom = "Découvrez l'architecture des logiciels",
                            NomSeo = "architecture-des-logiciels"
                        },
                        new
                        {
                            Id = 7,
                            Description = "comment faire du C",
                            Nom = "Apprendre le React.JS",
                            NomSeo = "langage-react.js"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Android est un système d'exploitation mobile fondé sur le noyau Linux",
                            Nom = "Le langage androïd en plusieurs étapes",
                            NomSeo = "langage-androïd"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Découvrez le code avec PHP",
                            Nom = "Apprendre le PHP",
                            NomSeo = "langage-php"
                        });
                });

            modelBuilder.Entity("Data.ReRouting", b =>
                {
                    b.Property<string>("OldUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NewUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OldUrl");

                    b.ToTable("ReRouting");
                });

            modelBuilder.Entity("Data.Avis", b =>
                {
                    b.HasOne("Data.Formation", "Formation")
                        .WithMany("Avis")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
